### ISSUE TITLE
Voltron question about Xenium to Visium transfer

### ISSUE THREAD

**Issue by vraghu90** [BIMSBbioinfo/VoltRon#143]
I received the following warning when using the transfer data function for  Xenium to Visium transfer, but was able to properly use vrSpatialFeaturePlot. What does this mean?
In vrCoordinates.vrAssay(from_object, reg = TRUE) : There are no registered spatial systems with name main!

Futhermore, I'm noticing that not all the visium spots are visible in the visum_pseudo plot image, and seems to be only covering a portion of the image. Is this related to the first error? Shouldn't an equal number of spots be represented between visium and visium_pseudo?

I am following the instructions here, for 1 visium and 1 xenium exp on the same sample:
https://bioinformatics.mdc-berlin.de/VoltRon/registration.html

**Comment by Artur-man** [comment]
Hello there, 

I have just pushed an update to the [dev](https://github.com/BIMSBbioinfo/VoltRon/tree/dev) branch. Essentially now the `transferData` function should not ask for registered coordinate systems out of blue, instead `registerSpatialData` function now should set the main spatial coordinates as the registered ones upon registration which then `transferData` uses this setting.  

Here is how it would look like:

```
xen_reg <- registerSpatialData(object_list = list(Xen_R1, Vis, Xen_R2))
merge_list <- xen_reg$registered_spat
VRBlock <- merge(merge_list[[1]], merge_list[-1], samples = "10XBlock")
vrSpatialNames(VRBlock, assay = "all")
```

You can see that both Xenium sections (Assays 1 and 3) are registered to Visium (Assay2) hence they have two coordinate systems where Xeniums' coordinate systems are switched to `main_reg` while Visium's stayed the same (since there is only a single one).

```
   Assay       Spatial     Main
1 Assay1 main,main_reg main_reg
2 Assay2          main     main
3 Assay3 main,main_reg main_reg
``` 

Now you can visualize where we have the registered coordinates as the default one. 

```
vrSpatialFeaturePlot(VRBlock, assay = "Assay1", plot.segments = TRUE,
                     crop = TRUE, features = "KRT15")
```

![image](https://github.com/user-attachments/assets/aa95d0ca-2fd7-416c-b0d0-ec8444af27c5)

Switching back to the original coordinate system

```
vrSpatialFeaturePlot(VRBlock_new, assay = "Assay1", plot.segments = TRUE, 
                     features = "KRT15", background = "main")
```

![image](https://github.com/user-attachments/assets/20be4330-dea4-4d32-931e-3c1d1466d312)

**Comment by Artur-man** [comment]
Yes! you need to remove the package with `remove.packages("VoltRon")` (do it again just to make sure), then restart R session and install it again but from the dev branch `devtools::install_github("BIMSBbioinfo/VoltRon@dev")`

**Comment by vraghu90** [comment]
So I'm still running into the issue where the Visium_pseudo output consists
of spots which cover only a portion of the image.

---

*Vineeth Raghuram, Ph.D.*

*(603)-943-0489*

**Comment by Artur-man** [comment]
I think that is because only some of the Xenium cells overlap with the Visium spots, since we aggregate Xenium cells into Visium spots to create the pseudo assay. 

You can see the change in the spot set across the `Visium` and `Visium_pseudo` assays. Here observe that new Visium spots simply overlay with the globally aligned Xenium DAPI image. 

![image](https://github.com/user-attachments/assets/e9168671-1e29-4e5b-ba1b-9f497606dde1)

Also see: https://bioinformatics.mdc-berlin.de/VoltRon/registration.html#Data_Transfer

Please let me know if you wanna suggest additional utilities of the function: would you also like to generate empty spot upon `transferData` ?

**Comment by Artur-man** [comment]
Alternatively, if you are concerned with the H&E image not covered with Visium spots, this is simply because of the design of the Visium slide, not all spots can cover the entire area. I am trying to find an example to show that. 

However, you can use the `crop = TRUE` arguement in both `vrSpatialPlot` and `vrSpatialFeaturePlot` functions to crop the span of the Visium spots.

**Comment by vraghu90** [comment]
So both my visium and xenium experiments cover the same area of tissue
(there is full overlap) so I would expect the spot integration to be
present throughout the image.

---

*Vineeth Raghuram, Ph.D.*

*(603)-943-0489*

**Comment by Artur-man** [comment]
Now the Automated and Manual Alignment tutorial include a small explanation on how reference and query images should be provided when there is only single reference and query image in the list. 

https://github.com/BIMSBbioinfo/VoltRon/blob/049cbaeb3f380454b070f8b4cff10364aa29555f/docs/registration.Rmd#L144-L150

After alignment, the `transferData` function can be used to transfer counts from Xenium to Visium as below. Here, `Assay2` is the Xenium assay and `Assay1` is the Visium assay. 

```
merge_list <- xen_reg$registered_spat
VRBlock <- merge(merge_list[[1]], merge_list[-1], samples = "10XBlock")
VRBlock <- transferData(VRBlock, from = "Assay2", to = "Assay1")
```

Lets visualize all assays whose coordinates are syncronized (Here Visium is the reference spatial data in the tissue block).

```
library(patchwork)
g1 <- vrSpatialFeaturePlot(VRBlock_new, assay = "Assay1", features = "ERBB2")
g2 <- vrSpatialFeaturePlot(VRBlock_new, assay = "Assay3", features = "ERBB2")
g3 <- vrSpatialFeaturePlot(VRBlock_new, assay = "Assay2", features = "ERBB2", plot.segments = TRUE, alpha = 1)
(g1 | g2 | g3)
```
<img width="1424" alt="Screenshot 2024-09-20 at 23 32 05" src="https://github.com/user-attachments/assets/9d38c863-4a4d-4007-bf55-90e8fe49009c">

For now, we don't suggest designating the images of Visium assays as the query images, since the coordinate transformation for spot-level spatial datasets still needs some work. 

However, transfering data from Xenium to Visium should work as expected, under the condition that Xenium DAPI image is the query and Visium H&E image is the reference image.
